#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
sh $HOME/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr
bspc monitor -d      

bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#282a36"
bspc config active_border_color "#bbbbbb"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
