#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
dunst &
sh $HOME/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr
#----------workspace-----------------------------------------------------------#
bspc monitor -d こ ん に ち は
#-------------------------------------------------------------------------------#
bspc config focused_border_color "#F0AFE1"
bspc config normal_border_color "#bbbbb"
bspc config active_border_color "#C6AAE8"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#---------terminal------------------------------------#
bspc rule -a alacritty desktop="^1" follow=on focus=on
#---------video-player--------------------------------#
bspc rule -a mpv desktop="^4" follow=on focus=on
#---------browser-------------------------------------#
#bspc rule -a firefox desktop="^2" follow=on focus=on
bspc rule -a brave desktop="^2" follow=on focus=on
#-------spotify---------------------------------------#
bspc rule -a spotify desktop="^4" follow=on focus=on
#------discord----------------------------------------#
bspc rule -a discord desktop="^3" follow=on focus=on
########################################EOF############################################
